apiVersion: v1
kind: ReplicationController
metadata: 
  name: etcd1
  labels:
    name: etcd1
  namespace: cloudtest
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: etcd1
    spec:
      containers:
      - name: etcd1
        image: localhub:5000/cloudtest/etcd-amd64:2.2.5
        args:
        - /bin/bash
        - -c
        - etcd -name etcd1 -data-dir /var/etcd/data -listen-peer-urls http://0.0.0.0:2380 -listen-client-urls http://0.0.0.0:4001 -initial-advertise-peer-urls http://etcd1:2380 -initial-cluster etcd0=http://etcd0:2380,etcd1=http://etcd1:2380,etcd2=http://etcd2:2380 -initial-cluster-state new -initial-cluster-token etcd-cluster -advertise-client-urls http://etcd1:4001
        ports:
        - containerPort: 2380
	  name: peerPort
        - containerPort: 4001
	  name: clientPort
      restartPolicy: Always
