apiVersion: v1
kind: Service
metadata:
  name: etcd0
  labels:
    name: etcd0
  namespace: cloudtest
spec:
  selector:
    name: etcd0
  ports:
  - port: 2380
    targetPort: 2380
    name: peerPort
  - port: 4001
    targetPort: 4001
    name: clientPort
